=== dataprev/ckan-loader/src/main/resources/br/gov/dados/script/config/xsd/ckan-config.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified" targetNamespace="http://www.dados.gov.br/ns/script/ckan-config"
	xmlns:dados="http://www.dados.gov.br/ns/script/ckan-config">
	
	<xs:element name="ckan-config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ckan-config-params" minOccurs="1"
					maxOccurs="unbounded" type="dados:ckan-config-params-type">
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="ckan-config-params-type">
		<xs:sequence>
			<xs:element name="ckan-connection" minOccurs="1" maxOccurs="1">
				<xs:complexType>
					<xs:all>
						<xs:element name="url-api" type="xs:string"
							minOccurs="1" maxOccurs="1" />
						<xs:element name="api-key" type="xs:string" minOccurs="1"
							maxOccurs="1" />
					</xs:all>
				</xs:complexType>
			</xs:element>

			<xs:element name="ckan-dataset" maxOccurs="unbounded">
				<xs:complexType>
					<xs:all>
						<xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="title" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="url" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="author" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="author-email" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="maintainer" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="maintainer-email" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="license-id" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="notes" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="tags" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="state" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="organization" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="resources-csv-path" type="xs:string" minOccurs="1" maxOccurs="1" />
						<xs:element name="groups-csv-path" type="xs:string" minOccurs="1" maxOccurs="1" />
						<!-- criar elemento que considere key/value  -->
						<!--<xs:element name="" type="xs:string" minOccurs="0" maxOccurs="unbounded" /> -->
					</xs:all>
				</xs:complexType>
			</xs:element>

		</xs:sequence>
		<xs:attribute name="name" type="xs:string" use="required">
			<xs:annotation>
				<xs:documentation>
					Referência do dataset que será carregado pelo script.
				</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
</xs:schema>

=== dataprev/ckan-loader/env/ckan-config.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<dados:ckan-config xmlns:dados="http://www.dados.gov.br/ns/script/ckan-config"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.dados.gov.br/ns/script/ckan-config ../br/gov/dados/script/config/xsd/ckan-config.xsd ">
	
	<dados:ckan-config-params name="dev">
	
		<!-- CKAN API Connection details -->
		<dados:ckan-connection>
			<dados:url-api>http://ckan.dados.gov.br/api</dados:url-api>
			<dados:api-key></dados:api-key>
		</dados:ckan-connection>
		
		<!-- Datasets -->
		
		<dados:ckan-dataset>
			<dados:name>sample1-dataset</dados:name>
			<dados:title>Sample Dataset</dados:title>
			<dados:url></dados:url>
			<dados:author></dados:author>
			<dados:author-email></dados:author-email>
			<dados:maintainer>Foo Bar</dados:maintainer>
			<dados:maintainer-email>foo.bar@dados.gov.br</dados:maintainer-email>
			<dados:license-id>cc-by-sa</dados:license-id>
			<dados:version></dados:version>
			<dados:notes></dados:notes>
			<dados:tags></dados:tags>
			<dados:state></dados:state>
			<dados:organization></dados:organization>
			<dados:resources-csv-path>csv/sample1.csv</dados:resources-csv-path>
			<dados:groups-csv-path></dados:groups-csv-path>
		</dados:ckan-dataset>

		<dados:ckan-dataset>
			<dados:name>sample2-dataset</dados:name>
			<dados:title>Colors JSON</dados:title>
			<dados:url></dados:url>
			<dados:author></dados:author>
			<dados:author-email></dados:author-email>
			<dados:maintainer>Foo Bar</dados:maintainer>
			<dados:maintainer-email>foo.bar@dados.gov.br</dados:maintainer-email>
			<dados:license-id>cc-by-sa</dados:license-id>
			<dados:version></dados:version>
			<dados:notes>Colors Hex value JSON</dados:notes>
			<dados:tags></dados:tags>
			<dados:state></dados:state>
			<dados:organization></dados:organization>
			<dados:resources-csv-path>csv/sample2.csv</dados:resources-csv-path>
			<dados:groups-csv-path></dados:groups-csv-path>
		</dados:ckan-dataset>
			
		
	</dados:ckan-config-params>
	
</dados:ckan-config>
